# syntax=docker/dockerfile:1

ARG RUBY_VERSION=3.3.11
FROM docker.io/library/ruby:${RUBY_VERSION}-bookworm

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      curl \
      git \
      libpq-dev \
      libyaml-dev \
      pkg-config \
      postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV BUNDLE_JOBS="4" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_RETRY="3"

COPY Gemfile Gemfile.lock* ./
RUN bundle install

COPY . .

ENTRYPOINT ["./bin/docker-entrypoint"]
EXPOSE 3000
CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
